Use a random string for the CSRF_TOKEN in tests, rather than a bigint
When running tests locally, I would get the following error:

```
WebExtension::when there is failure#test_0004_can retry failure:
NoMethodError: undefined method `empty?' for 154175120175936854824448130840853429553:Bignum
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/authenticity_token.rb:122:in `valid_token?'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/authenticity_token.rb:103:in `accepts?'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:46:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web.rb:103:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web.rb:108:in `call'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
    /Users/mattcasper/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-test-1.1.0/lib/rack/test.rb:66:in `post'
    /Users/mattcasper/code/home/sidekiq-failures/test/web_extension_test.rb:175:in `block (3 levels) in <module:Sidekiq>'
```

This seems to come from the fact that we're setting our
HTTP_X_CSRF_TOKEN header in tests as a bigint, when the rack-protection
library expects it to be a string and to respond to `empty?`. This
commits changes the test to generate a CSRF token the same way
rack-protection does.